name: Build and Release APK/AAB

on:
  workflow_dispatch:

env:
  VOCAB_KEYSTORE_FILE: /tmp/vocab-keystore.jks
  #  VOCAB_KEYSTORE_FILE: ${{ secrets.VOCAB_KEYSTORE_JSK }}
  VOCAB_KEYSTORE_PASSWORD: ${{ secrets.VOCAB_KEYSTORE_PASSWORD }}
  VOCAB_KEY_ALIAS: ${{ secrets.VOCAB_KEY_ALIAS }}
  VOCAB_KEY_PASSWORD: ${{ secrets.VOCAB_KEY_PASSWORD }}

jobs:
  build:
    name: Apk/AAB Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - run: flutter pub get

      - name: Setup Keystore
        run: |
          echo "${{ secrets.VOCAB_KEYSTORE_JSK }}" | base64 -d > $VOCAB_KEYSTORE_FILE
          ls -la

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab